### PR TITLE
Extension frontend

### LINKED ISSUE #2: Extension Front-End
Translate the approved designs into code. Build the front end using HTML, CSS, and JavaScript, ensuring responsiveness and cross-browser compatibility. Implement the UI components as per the design document.

Deliverable: A functional front-end of the browser extension, demonstrating the core UI without backend integration.

### PR DESCRIPTION
**Pull request by michaelehab**
Fix #2 
# Updates
- I added Frontend files using Bulma CSS as we discussed in a previous meeting.
- The frontend design is very close to the VulnerableCode website.
- I added the Full-Screen button as we discussed in a previous meeting.
- I extracted a real JSON response from VulnTotal, corresponding to "pkg:pypi/jinja2@2.4.1" purl, and used the response to show how the extension should behave with real data.
# Screenshots
## Popup
environment loading
hero part

## Full Screen
home page
settings page
results table

### CODE REVIEW

**Comment by OmkarPh** [comment]
UI is looking good !

Change font color on hovering links, so that it looks like
image

instead of
image

**Comment by OmkarPh** [comment]
On clicking settings button, it opens a new tab (regardless of whether I'm in full screen or smaller window)

If i do, settings -> back to home -> settings -> back to home
This results unnecessary tabs, we should ideally open settings in the same window ?

**Comment by michaelehab** [comment]
I agree!
I updated the hover effect for the navigation links.
image
image
I also updated the links behaviors, making sure we only open a new tab if the active tab does not belong to VulnTotal.

**Comment by michaelehab** [comment]
@OmkarPh Please review and accept the PR if it looks good, we need to merge it.

**Comment by OmkarPh** [comment]
> On clicking settings button, it opens a new tab (regardless of whether I'm in full screen or smaller window)
> 
> If i do, settings -> back to home -> settings -> back to home This results unnecessary tabs, we should ideally open settings in the same tab?

This is still occurring for me, LGTM otherwise

**Comment by OmkarPh** [comment]
@keshav-space please have a look too

**Comment by michaelehab** [comment]
Hi @OmkarPh @keshav-space, I updated the frontend based on the comments I received during our weekly meetings. 
I used tags to distinct comma separated values for versions, and I added datasources logos.
I also expanded the results table as instructed.
image

**Review by keshav-space — CHANGES_REQUESTED** [review]
Looking Good @michaelehab!
Please remove the files and config that are not required for extension project like setup.cfg, requirements.txt, etc..
Also edit the README for now just having a couple of lines explaining what the project is works, and you can refine it during documentation phase.

**Comment by michaelehab** [comment]
@keshav-space Changes done, I kept the CI files.

**Review by keshav-space — APPROVED** [review]
Merging, thanks @michaelehab

**Pull request merged**
